// Site-wide settings. Change these in one place and every page, the sitemap,
// structured data and llms.txt pick them up.

export const site = {
  // The brand in running text. The logo lockup and legal name are set separately.
  name: 'Momixx',
  legalName: 'Orion MoMixx',
  // Company registration number (Singapore UEN). Shown in the footer once filled in.
  registrationNumber: '201310727R',
  // Canonical origin. The live WordPress site serves www.momixx.com, so we keep
  // www as canonical to preserve existing search rankings.
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://www.momixx.com',
  tagline: 'High-performance and recycled silicone, engineered in Asia for the world.',
  description:
    'Momixx develops, recycles and processes high-performance silicone for cables, electric vehicles, medical devices, AI data centres and robotics. Headquartered in Singapore, with manufacturing in Asia including Penang, Malaysia.',
  foundingYear: 2019,
  email: 'enquiries@orionmomixx.com',
  // Optional dedicated inboxes; each falls back to the enquiries address when empty.
  careersEmail: '',
  investorEmail: '',
  address: {
    street: '22 New Industrial Road, #03-09/10 Primax',
    locality: 'Singapore',
    postalCode: '536208',
    country: 'SG',
  },
  locations: [
    { name: 'Singapore', role: 'Headquarters', detail: '22 New Industrial Road, Primax' },
    { name: 'Batu Kawan, Penang, Malaysia', role: 'Research and manufacturing', detail: 'Liquid silicone, certified medical parts and precision parts' },
  ],
  // Add LinkedIn etc. here once confirmed; they feed Organization.sameAs.
  sameAs: [] as string[],
} as const

export function absoluteUrl(path = '/') {
  return new URL(path, site.url).toString()
}

/**
 * Search results show about 155–160 characters of a description. Longer text is
 * cut at the last full sentence that fits, or else at a word, never mid-word.
 */
export function metaDescription(text: string, max = 158) {
  const clean = text.replace(/\s+/g, ' ').trim()
  if (clean.length <= max) return clean
  const sentences = clean.match(/[^.!?]+[.!?]+(\s|$)/g) ?? []
  let out = ''
  for (const sentence of sentences) {
    if ((out + sentence).trim().length > max) break
    out += sentence
  }
  if (out.trim().length >= 70) return out.trim()
  const cut = clean.slice(0, max - 1)
  return `${cut.slice(0, cut.lastIndexOf(' ')).replace(/[,;:\s]+$/, '')}…`
}

/**
 * Per-page metadata with a self-referencing canonical URL. Every page must set
 * its own canonical, otherwise search engines may treat pages as duplicates.
 */
export function pageMetadata({
  title,
  description: text,
  path,
  ownImage = false,
}: {
  title: string
  description: string
  path: string
  /** The route has its own opengraph-image file, so don't point at the shared one. */
  ownImage?: boolean
}) {
  const description = metaDescription(text)
  return {
    title,
    description,
    alternates: {
      canonical: path,
      // Every page points feed readers at the Insights feed.
      types: { 'application/rss+xml': [{ url: '/insights/feed.xml', title: `${site.name} Insights` }] },
    },
    openGraph: {
      title,
      description,
      url: path,
      siteName: site.legalName,
      type: 'website' as const,
      locale: 'en_SG',
      // Setting openGraph on a page replaces the root one, so re-attach the
      // shared social image generated by app/opengraph-image.tsx, unless the
      // route makes its own (an explicit image here would override that file).
      ...(ownImage ? {} : { images: [{ url: '/opengraph-image', width: 1200, height: 630, alt: `${site.name}: ${site.tagline}` }] }),
    },
  }
}
