// Site-wide settings. Change these in one place and every page, the sitemap,
// structured data and llms.txt pick them up.

export const site = {
  name: 'Momixx',
  legalName: 'Orion MoMixx',
  // Canonical origin. The live WordPress site serves www.momixx.com, so we keep
  // www as canonical to preserve existing search rankings.
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://www.momixx.com',
  tagline: 'High-performance and recycled silicone, engineered in Asia for the world.',
  description:
    'Momixx develops, recycles and processes high-performance silicone for cables, electric vehicles, medical devices, AI data centres and robotics. Headquartered in Singapore with plants in Penang, Malaysia and Guangdong, China.',
  foundingYear: 2018,
  email: 'enquiries@orionmomixx.com',
  address: {
    street: '22 New Industrial Road, #03-09/10 Primax',
    locality: 'Singapore',
    postalCode: '536208',
    country: 'SG',
  },
  locations: [
    { name: 'Singapore', role: 'Headquarters', detail: '22 New Industrial Road, Primax' },
    { name: 'Batu Kawan, Penang, Malaysia', role: 'R&D and manufacturing', detail: 'LSR production, medical (ISO 13485) and precision components' },
    { name: 'Dongguan, Guangdong, China', role: 'Manufacturing', detail: 'Large-volume silicone production since 2022' },
  ],
  // Add LinkedIn etc. here once confirmed; they feed Organization.sameAs.
  sameAs: [] as string[],
} as const

export type NavItem = { href: string; label: string; children?: NavItem[] }

export const mainNav: NavItem[] = [
  { href: '/silicone', label: 'Silicone' },
  { href: '/products', label: 'Products' },
  { href: '/applications', label: 'Applications' },
  { href: '/recycled-silicone', label: 'Recycled Silicone' },
  { href: '/markets', label: 'Markets' },
  {
    href: '/about',
    label: 'Company',
    children: [
      { href: '/about', label: 'About Us' },
      { href: '/team', label: 'Our Team' },
      { href: '/innovation', label: 'Research & Innovation' },
    ],
  },
]

export function absoluteUrl(path = '/') {
  return new URL(path, site.url).toString()
}

/**
 * Per-page metadata with a self-referencing canonical URL. Every page must set
 * its own canonical, otherwise search engines may treat pages as duplicates.
 */
export function pageMetadata({ title, description, path }: { title: string; description: string; path: string }) {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: path,
      siteName: site.legalName,
      type: 'website' as const,
      locale: 'en_SG',
      // Setting openGraph on a page replaces the root one, so re-attach the
      // shared social image generated by app/opengraph-image.tsx.
      images: [{ url: '/opengraph-image', width: 1200, height: 630, alt: `${site.name}: ${site.tagline}` }],
    },
  }
}
